# Generated by Django 4.0.1 on 2022-05-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_userid_supplier_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('pricePerQty', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
                ('tenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qtyInStock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('proImg', models.ImageField(upload_to='Product_Img')),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='catId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
            preserve_default=False,
        ),
    ]
