# Generated by Django 4.0.1 on 2022-06-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_tender_quotation_product_supplier_catid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='qty',
        ),
        migrations.CreateModel(
            name='TenderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('tenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tender')),
            ],
        ),
    ]
