# Generated by Django 4.0.1 on 2022-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_tender_productname_remove_tender_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileNo',
            field=models.IntegerField(blank=True),
        ),
    ]
