# Generated by Django 4.0.1 on 2022-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tender_fullfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetails',
            name='tenderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='accounts.tender'),
        ),
    ]
