# Generated by Django 4.0.5 on 2023-10-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_address_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='supplierId',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='tenderId',
            new_name='tender',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='tenderdetails',
            name='tenderId',
        ),
        migrations.AddField(
            model_name='quotation',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderdetails',
            name='tender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.tender'),
            preserve_default=False,
        ),
    ]
