# Generated by Django 4.0.5 on 2023-10-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_supplierid_quotation_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
