# Generated by Django 4.0.5 on 2023-10-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_quotation_product_remove_quotation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quatation_status',
            field=models.BooleanField(default=False),
        ),
    ]
