# Generated by Django 4.0.5 on 2023-10-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_quotation_quatation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='quatation_status',
            new_name='quotation_status',
        ),
    ]
